---
.travis.yml:
  secure: "YejrB/mfwOdZGDCL5ciyCnZ9aAv6bAXgOhzNYx2l5NEYMN6iJqvPdL8ha1CHasxfQSdDX/7eUstD9blGYhTaW7EzY1CnZDfjQ1ldyV5bXHsWHGWrSMisvGmcGDzkwvpoQtQg2INMRWwbVE7e7WE/DXI41TbYuh032wB7wa75NzqlUFczPnJ4hWWt48wA9iebMOU0yk6k6cbKNj4lOBH5EiEjF1u0SUKnvOD5nFET439+r5CgZqPRDMHoAJhUCX7B+UMs1I64VPI9IJ9UW3XqaGkmts7NF4IUnInhGLxrm9+WXl8nlUC4IlC6V+TPTkVjE88tSLhs08WJqTb8C5/tkcsNB8KUBKygGkLnXiq5yzqq4VweErBxign95aAZyo5WEmHqEX82K/W9THzui6LCMruc+MKWl4L8pDus1rtBebZOdSGiJH2MPOo1o/p+essHDgsBayhdIVuLpqx/TMeLa6dpoesiiVgxXPh6Zr+9HdOE2oclVAwF/8qOrF+YaGyffhOUsT9Dcqq9Czg+8GXPjdJtUCXBWvOOj1jt+EZ6JZCWOVYWVzhGPUC1gRfB7UXle7/tNYZrCcg87/fh6UnRDv5EFZam9rFp6vL0MUnLob+PyY4eUsaefnQyGLnHYrJbaNmaaX6q0qeQ8fJmt4dQUrby2e0h+ZAcs9Zv+9Pvlpw="
spec/spec_helper_acceptance.rb:
  unmanaged: false
spec/acceptance/nodesets/archlinux-2-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  unmanaged: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  unmanaged: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  unmanaged: true
